[licenses]
allow-osi-fsf-free = "either"
copyleft = "deny"
exceptions = [{ allow = ["ISC", "MIT", "OpenSSL"], name = "ring" }]

[[licenses.clarify]]
name = "ring"
expression = "ISC AND MIT AND OpenSSL"
license-files = [{ path = "LICENSE", hash = 0xbd0eed23 }]
